### PR TITLE
Unify 'CMAKE_*_DIR'

### PR DESCRIPTION
**Pull request by ruslo**
Depends on https://github.com/patrikhuber/eos/pull/84

### CODE REVIEW

**Comment by patrikhuber** [comment]
Thanks, and interesting link!

I'm not completely sold yet on replacing `CMAKE_CURRENT_SOURCE_DIR ` with `CMAKE_CURRENT_LIST_DIR`. In the link, there's no explanation on why the latter should be used over the former:

> CMAKE_CURRENT_SOURCE_DIR this is a directory with CMakeLists.txt. If you’re using this variable internally you can substitute is with CMAKE_CURRENT_LIST_DIR.

_Edit:_ Ah, [this link](http://stackoverflow.com/questions/15662497/in-cmake-what-is-the-difference-between-cmake-current-source-dir-and-cmake-curr) gives some explanation... looks like it is indeed better to use `CMAKE_CURRENT_LIST_DIR` :-)

**Comment by ruslo** [comment]
> Ah, [this link](http://stackoverflow.com/questions/15662497/in-cmake-what-is-the-difference-between-cmake-current-source-dir-and-cmake-curr) gives some explanation

Actually when I hit this problem first time I've read the SO answer like 5 times and didn't get an understanding. I think here are better explanation:
* http://cgold.readthedocs.io/en/latest/tutorials/cmake-sources/includes.html#cmake-current-list-dir-vs-cmake-current-source-dir
* http://cgold.readthedocs.io/en/latest/tutorials/cmake-sources/includes.html#example

> there's no explanation on why the latter should be used over the former

There is no difference in current case because all the files with CMake code is CMakeLists.txt. However CMAKE_CURRENT_LIST_DIR is more universal and works fine in other cases too.

**Comment by patrikhuber** [comment]
Yes, I had to read the SO answer for a few times as well. I think we got the same understanding of it now.

**Comment by ruslo** [comment]
Conflicts resolved, ready to be merged.

**Comment by ruslo** [comment]
> Conflicts resolved, ready to be merged

One more time.

**Comment by patrikhuber** [comment]
Sorry for taking so long! I currently think changing it to `CMAKE_CURRENT_SOURCE_DIR` is fine, as it's more common than `CMAKE_CURRENT_LIST_DIR`. I will take care of resolving the conflicts of this PR if more emerge, thank you for your persistence! :-D

Would using `CMAKE_CURRENT_SOURCE_DIR` create any issues for Hunter, so does it depend on `CMAKE_CURRENT_LIST_DIR`? In that case I would be convinced!

Thanks again!

**Comment by ruslo** [comment]
> Would using CMAKE_CURRENT_SOURCE_DIR create any issues for Hunter, so does it depend on CMAKE_CURRENT_LIST_DIR? In that case I would be convinced!

No, it's not related to Hunter at all.

> I currently think changing it to CMAKE_CURRENT_SOURCE_DIR is fine, as it's more common than CMAKE_CURRENT_LIST_DIR.

Changing `CMAKE_CURRENT_SOURCE_DIR` -> `CMAKE_CURRENT_LIST_DIR` or keeping `CMAKE_CURRENT_SOURCE_DIR`?

**Comment by patrikhuber** [comment]
> No, it's not related to Hunter at all.

Ok, cool!

> Changing CMAKE_CURRENT_SOURCE_DIR -> CMAKE_CURRENT_LIST_DIR or keeping CMAKE_CURRENT_SOURCE_DIR?

I think currently some variables are still `CMAKE_SOURCE_DIR`, and this is definitely a mistake. I fixed this in another branch, I'll merge this soon. So all of these variables should be `CMAKE_CURRENT_SOURCE_DIR` (or alternatively as you mentioned `CMAKE_CURRENT_LIST_DIR` but I think I prefer the first one since it is sufficient in our case).

**Comment by ruslo** [comment]
> some variables are still CMAKE_SOURCE_DIR, and this is definitely a mistake

Yes, this may cause troubles when `eos` used as a subproject that added by `add_subdirectory`.

> I think I prefer the first one since it is sufficient in our case

Okay, closing this one then.

**Comment by patrikhuber** [comment]
I've taken all your changes and put them in PR #98! I just used `CMAKE_CURRENT_SOURCE_DIR` everywhere instead of `CMAKE_CURRENT_LIST_DIR`. I hope I didn't forget any of them :-)

Thanks again for your contributions.

**Pull request closed without merging**
