### PR TITLE
Tabs to spaces

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by patrikhuber** [comment]
Thank you very much for your contributions!

Is there any particular advantage of using 2 spaces in the CMake files? Pretty much all of `eos` uses tabs - I'm not particularly advocating for tabs over spaces but I'm kind of inclined to keep the code base with tabs.  And having a different convention for the CMake and C++ files would be a bit weird I think. I think with a proper editor, the user can always choose locally how they want to display the code anyway? And probably it would be best to have a .clang-format file in the repo... (I'll try to get to adding that!)

**Comment by ruslo** [comment]
> Is there any particular advantage of using 2 spaces in the CMake files?

Not any CMake specific, just regular one like same rendering for all users.

>  Pretty much all of eos uses tabs

Spaces here:
* https://github.com/patrikhuber/eos/blob/fc2f518efe323563b7bbb276c3175dccbe00e0bd/CMakeLists.txt#L52

There are no tabs, just spaces in `{doc,utils,example}/CMakeLists.txt` code.

> I'm not particularly advocating for tabs over spaces but I'm kind of inclined to keep the code base with tabs

To be clear, I'm not interested in just one more discussion about spaces vs. tabs and I'm planning to follow your rules. However I have to mention that it will be easier for me to contribute with spaces. I've never seen the style guide where tabs are preferable:
* [Qt](http://wiki.qt.io/Qt_Coding_Style) `Spaces, not tabs!`
* [Google](https://google.github.io/styleguide/cppguide.html#Spaces_vs._Tabs) `Do not use tabs in your code`
* [LLVM](http://llvm.org/docs/CodingStandards.html#use-spaces-instead-of-tabs) `In all cases, prefer spaces to tabs in source files`
* [Boost](http://www.boost.org/doc/libs/1_62_0/libs/spirit/doc/html/spirit/notes/style_guide.html) `use spaces instead of tabs`
* [Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Coding_Style) `No tabs`
* [KDE](https://community.kde.org/Policies/Kdelibs_Coding_Style#Indentation) `No tabs`

> I think with a proper editor, the user can always choose locally how they want to display the code anyway?

I don't think I can set 'tabs > spaces' for your local project and keep using 'spaces > tabs' for the rest. I can be wrong but I think there is no such settings for GVim (for example), like using `/path/to/tabs-config/.vimrc` for `eos` folder and all descending directories, and `~/.vimrc` for all others project.

**Comment by patrikhuber** [comment]
Thank you very much for your comments! I am inclined to agree. And good that you caught the existing inconsistencies. Let me think about this for a bit :-)

**Comment by patrikhuber** [comment]
After some pondering, I think spaces are a good idea. It will make for a more consistent style on all platforms/editors. I was for example always annoyed that GitHub displays tabs with a width of 8, which doesn't look very pretty.

So let's have 4 spaces as guideline. We can start with the CMakeLists! I'm happy to try pulling your branch and try adjusting it by myself and then pushing to this PR - no idea if that works though! :-)

I'll put a `.clang-format` file in the repo in the future, but I've had some problems with the clang-format VS plugin, so I'll leave that to the future.

**Comment by ruslo** [comment]
Pull request updated - conflicts resolved.

**Comment by patrikhuber** [comment]
Thank you very much!

**Pull request merged**
